# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a49f07139c3aace617fc82ff28d70bbc5462b76919e7be502884d3b8d2886f72c95cf29ef670998163f59857911c123b698e66f3ea0c586723befe6649c2ac5

test:
  secret_key_base: 895177a9c3132b6f1a61ca79834b33d5db2298796d22de87728f5fcf63198a28ae7e14c7f5d788a1dcb3d254b9965095029b2ec36522fdf52635cc8d1d9c9202

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
